<br>
<body style="font-family: sans-serif" onload="window.print()">    

<br>
    <center><img width="400px" src="/img/{{ $read['cover_book'] }}" alt=""></center>
    <center><b>{{ $read['title'] }}</b></center>
    <center><b>{{ $read['writter'] }}</b></center>
    <center><b>{{ $read['publisher'] }}</b></center>
    <center><b>{{ $read['ISBN'] }}</b></center>
    <br>
   <center>
        <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis vero, impedit totam officiis cupiditate aliquid aliquam cumque minima rem beatae nihil magnam iure perspiciatis voluptatem quae cum ratione nemo culpa libero repudiandae ullam accusamus nulla ut recusandae. Culpa quisquam incidunt vero totam eaque iure alias laudantium nobis aspernatur placeat sunt impedit eius quia dignissimos est quaerat nesciunt dolorem suscipit ipsum quo obcaecati aliquid, tempore veniam! Veniam, dolor esse? Rerum voluptas animi iusto aperiam cumque labore, illum quas mollitia sint autem, vitae voluptatum dicta nemo! Ipsum corrupti libero corporis deserunt aperiam harum dolorem, alias odio exercitationem quod accusamus sapiente provident vitae, ipsam, autem a in accusantium. Odit quis eaque deserunt nihil mollitia et praesentium enim aliquam veritatis dolore iure ipsum iste commodi id, beatae, corrupti sapiente tempora reprehenderit nemo modi doloribus. Voluptate ipsa ex tempora modi aliquam. Facere quibusdam aspernatur nam asperiores quaerat doloremque omnis mollitia magnam tempore! Officiis laborum magni totam modi quia exercitationem itaque explicabo commodi. Modi in, sequi voluptatem ex labore animi reiciendis sunt consequatur doloremque atque natus asperiores temporibus id architecto magnam obcaecati praesentium sint, molestias nulla. Aliquid porro excepturi voluptate neque! Atque blanditiis quaerat perferendis quam cumque, molestias enim tempora, voluptates, eveniet quisquam necessitatibus. Possimus corrupti laudantium quibusdam a omnis ipsum quas, fugit recusandae eos repudiandae sapiente eius quis cupiditate nobis sint corporis eveniet facilis ipsam unde facere accusamus rem dolore nostrum. Quos omnis ab, laborum pariatur illum exercitationem voluptas non esse fugit harum repellat eius. Maiores enim repellat, atque nostrum vitae nam dolorem itaque consequatur aut dolores consequuntur, rem voluptatem consectetur facilis, incidunt nulla laborum repudiandae asperiores sapiente reiciendis quos eveniet iure. Aliquid quis commodi deleniti dolorum rerum minima nesciunt velit numquam eaque nam quae reprehenderit, itaque animi in omnis fugit! Harum cum, perferendis voluptatum dignissimos veniam laboriosam ipsam magni officiis, voluptas necessitatibus laudantium aliquid.
        </p>
        <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis vero, impedit totam officiis cupiditate aliquid aliquam cumque minima rem beatae nihil magnam iure perspiciatis voluptatem quae cum ratione nemo culpa libero repudiandae ullam accusamus nulla ut recusandae. Culpa quisquam incidunt vero totam eaque iure alias laudantium nobis aspernatur placeat sunt impedit eius quia dignissimos est quaerat nesciunt dolorem suscipit ipsum quo obcaecati aliquid, tempore veniam! Veniam, dolor esse? Rerum voluptas animi iusto aperiam cumque labore, illum quas mollitia sint autem, vitae voluptatum dicta nemo! Ipsum corrupti libero corporis deserunt aperiam harum dolorem, alias odio exercitationem quod accusamus sapiente provident vitae, ipsam, autem a in accusantium. Odit quis eaque deserunt nihil mollitia et praesentium enim aliquam veritatis dolore iure ipsum iste commodi id, beatae, corrupti sapiente tempora reprehenderit nemo modi doloribus. Voluptate ipsa ex tempora modi aliquam. Facere quibusdam aspernatur nam asperiores quaerat doloremque omnis mollitia magnam tempore! Officiis laborum magni totam modi quia exercitationem itaque explicabo commodi. Modi in, sequi voluptatem ex labore animi reiciendis sunt consequatur doloremque atque natus asperiores temporibus id architecto magnam obcaecati praesentium sint, molestias nulla. Aliquid porro excepturi voluptate neque! Atque blanditiis quaerat perferendis quam cumque, molestias enim tempora, voluptates, eveniet quisquam necessitatibus. Possimus corrupti laudantium quibusdam a omnis ipsum quas, fugit recusandae eos repudiandae sapiente eius quis cupiditate nobis sint corporis eveniet facilis ipsam unde facere accusamus rem dolore nostrum. Quos omnis ab, laborum pariatur illum exercitationem voluptas non esse fugit harum repellat eius. Maiores enim repellat, atque nostrum vitae nam dolorem itaque consequatur aut dolores consequuntur, rem voluptatem consectetur facilis, incidunt nulla laborum repudiandae asperiores sapiente reiciendis quos eveniet iure. Aliquid quis commodi deleniti dolorum rerum minima nesciunt velit numquam eaque nam quae reprehenderit, itaque animi in omnis fugit! Harum cum, perferendis voluptatum dignissimos veniam laboriosam ipsam magni officiis, voluptas necessitatibus laudantium aliquid.
        </p>
        <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis vero, impedit totam officiis cupiditate aliquid aliquam cumque minima rem beatae nihil magnam iure perspiciatis voluptatem quae cum ratione nemo culpa libero repudiandae ullam accusamus nulla ut recusandae. Culpa quisquam incidunt vero totam eaque iure alias laudantium nobis aspernatur placeat sunt impedit eius quia dignissimos est quaerat nesciunt dolorem suscipit ipsum quo obcaecati aliquid, tempore veniam! Veniam, dolor esse? Rerum voluptas animi iusto aperiam cumque labore, illum quas mollitia sint autem, vitae voluptatum dicta nemo! Ipsum corrupti libero corporis deserunt aperiam harum dolorem, alias odio exercitationem quod accusamus sapiente provident vitae, ipsam, autem a in accusantium. Odit quis eaque deserunt nihil mollitia et praesentium enim aliquam veritatis dolore iure ipsum iste commodi id, beatae, corrupti sapiente tempora reprehenderit nemo modi doloribus. Voluptate ipsa ex tempora modi aliquam. Facere quibusdam aspernatur nam asperiores quaerat doloremque omnis mollitia magnam tempore! Officiis laborum magni totam modi quia exercitationem itaque explicabo commodi. Modi in, sequi voluptatem ex labore animi reiciendis sunt consequatur doloremque atque natus asperiores temporibus id architecto magnam obcaecati praesentium sint, molestias nulla. Aliquid porro excepturi voluptate neque! Atque blanditiis quaerat perferendis quam cumque, molestias enim tempora, voluptates, eveniet quisquam necessitatibus. Possimus corrupti laudantium quibusdam a omnis ipsum quas, fugit recusandae eos repudiandae sapiente eius quis cupiditate nobis sint corporis eveniet facilis ipsam unde facere accusamus rem dolore nostrum. Quos omnis ab, laborum pariatur illum exercitationem voluptas non esse fugit harum repellat eius. Maiores enim repellat, atque nostrum vitae nam dolorem itaque consequatur aut dolores consequuntur, rem voluptatem consectetur facilis, incidunt nulla laborum repudiandae asperiores sapiente reiciendis quos eveniet iure. Aliquid quis commodi deleniti dolorum rerum minima nesciunt velit numquam eaque nam quae reprehenderit, itaque animi in omnis fugit! Harum cum, perferendis voluptatum dignissimos veniam laboriosam ipsam magni officiis, voluptas necessitatibus laudantium aliquid.
        </p>
        <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis vero, impedit totam officiis cupiditate aliquid aliquam cumque minima rem beatae nihil magnam iure perspiciatis voluptatem quae cum ratione nemo culpa libero repudiandae ullam accusamus nulla ut recusandae. Culpa quisquam incidunt vero totam eaque iure alias laudantium nobis aspernatur placeat sunt impedit eius quia dignissimos est quaerat nesciunt dolorem suscipit ipsum quo obcaecati aliquid, tempore veniam! Veniam, dolor esse? Rerum voluptas animi iusto aperiam cumque labore, illum quas mollitia sint autem, vitae voluptatum dicta nemo! Ipsum corrupti libero corporis deserunt aperiam harum dolorem, alias odio exercitationem quod accusamus sapiente provident vitae, ipsam, autem a in accusantium. Odit quis eaque deserunt nihil mollitia et praesentium enim aliquam veritatis dolore iure ipsum iste commodi id, beatae, corrupti sapiente tempora reprehenderit nemo modi doloribus. Voluptate ipsa ex tempora modi aliquam. Facere quibusdam aspernatur nam asperiores quaerat doloremque omnis mollitia magnam tempore! Officiis laborum magni totam modi quia exercitationem itaque explicabo commodi. Modi in, sequi voluptatem ex labore animi reiciendis sunt consequatur doloremque atque natus asperiores temporibus id architecto magnam obcaecati praesentium sint, molestias nulla. Aliquid porro excepturi voluptate neque! Atque blanditiis quaerat perferendis quam cumque, molestias enim tempora, voluptates, eveniet quisquam necessitatibus. Possimus corrupti laudantium quibusdam a omnis ipsum quas, fugit recusandae eos repudiandae sapiente eius quis cupiditate nobis sint corporis eveniet facilis ipsam unde facere accusamus rem dolore nostrum. Quos omnis ab, laborum pariatur illum exercitationem voluptas non esse fugit harum repellat eius. Maiores enim repellat, atque nostrum vitae nam dolorem itaque consequatur aut dolores consequuntur, rem voluptatem consectetur facilis, incidunt nulla laborum repudiandae asperiores sapiente reiciendis quos eveniet iure. Aliquid quis commodi deleniti dolorum rerum minima nesciunt velit numquam eaque nam quae reprehenderit, itaque animi in omnis fugit! Harum cum, perferendis voluptatum dignissimos veniam laboriosam ipsam magni officiis, voluptas necessitatibus laudantium aliquid.
        </p>
    </center>
    <br>
</body>